name: Android Release

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: mkdir ~/android-env/
      - name: specify NDK
        run: |
          wget "https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip"
          unzip android-ndk-r14b-linux-x86_64.zip -d ~/android-env/

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Android sdk
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          export ANDROID_NDK=/home/runner/android-env/android-ndk-r14b
          export ANDROID_NDK_ROOT=/home/runner/android-env/android-ndk-r14b
          echo "y" | sudo apt-get install ninja-build
          echo "y" | sudo apt-get install tree
          . setup.env
          build_Android

      - name: Upload SDK
        uses: actions/upload-artifact@v2
        with:
          name: AndroidSDK
          path: output

